# Generated by Django 6.0.2 on 2026-02-28 12:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studysession",
            options={"ordering": ["date"]},
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={"ordering": ["exam_date"]},
        ),
        migrations.AddField(
            model_name="studysession",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studysession",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="hours_allocated",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0.1)]
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="daily_hours_available",
            field=models.FloatField(
                default=4.0,
                validators=[
                    django.core.validators.MinValueValidator(0.5),
                    django.core.validators.MaxValueValidator(16.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="difficulty",
            field=models.IntegerField(
                choices=[(1, "Easy"), (2, "Medium"), (3, "Hard")], default=2
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="syllabus_completion",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
