# Generated by Django 6.0.2 on 2026-03-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0002_alter_studysession_options_alter_subject_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="selected_topics",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
